"""drop unique constraint on submission_id

Revision ID: 7f391c0adde4
Revises: c5cf6510f3dc
Create Date: 2026-08-27 23:07:38.416932+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f391c0adde4'
down_revision: Union[str, Sequence[str], None] = 'c5cf6510f3dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Drop the unique constraint (if it exists)
    op.drop_constraint('receipts_submission_id_key', 'receipts', type_='unique')
    # Drop the unique index (safety net)
    op.execute("DROP INDEX IF EXISTS ix_receipts_submission_id;")
    

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
